CREATE OR REPLACE FUNCTION EOL_3_MONTH_AVG (
part_no_ in varchar2) return NUMBER
is
wip_ NUMBER;
CURSOR Get_3_Month_Avg IS
SELECT sum(QTY)/3
FROM IFSINFO.PRL_GROSS_PRFT_MPS
WHERE PART = part_no_ 
AND TRUNC(INV_DATE, 'MM') BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -3),'MM') AND TRUNC(ADD_MONTHS(SYSDATE, -1),'MM');
BEGIN
OPEN Get_3_Month_Avg;
FETCH Get_3_Month_Avg INTO wip_;
CLOSE Get_3_Month_Avg;
RETURN wip_;
END;
