CREATE OR REPLACE FUNCTION IFSAPP.PRL_CONVERT_100MINUTES(
TIME_1_ in NUMBER) return NUMBER
IS
HOURS_1 NUMBER;
MINUTES_1 NUMBER;
HOURS_S NUMBER;
MINUTES_S NUMBER;
Begin
HOURS_1 := TRUNC(TIME_1_);
MINUTES_1 := TIME_1_ - TRUNC(TIME_1_);
MINUTES_S := (MINUTES_1 * 1.666666);
--RETURN(MINUTES_S);
return ROUND(HOURS_1 + MINUTES_S,2);
END;

GRANT EXECUTE ON IFSAPP.PRL_CONVERT_100MINUTES TO IFSINFO WITH GRANT OPTION