     SELECT PARTY_TYPE_ID_PROPERTY.COMPANY,
            CUSTOMER_INFO.CUSTOMER_ID,
            CUSTOMER_INFO.NAME,
            CUSTOMER_INFO_ADDRESS.ADDRESS,
            CUSTOMER_INFO_COMM_METHOD.VALUE AS PHONE,
            CUSTOMER_INFO_COMM_METHOD_1.VALUE AS FAX,
            PARTY_TYPE_ID_PROPERTY.CODE,
            IFSAPP.INVOICE_PROPERTY_CODE_API.Get_Description (
               PARTY_TYPE_ID_PROPERTY.COMPANY,
               PARTY_TYPE_ID_PROPERTY.CODE)
               AS OUTSIDE_REP_DESCRIPTION,
            CUST_ORD_CUSTOMER.SALESMAN_CODE,
            IFSAPP.get_pricelist1 (CUSTOMER_INFO.CUSTOMER_ID) AS PRICELIST1,
            IFSAPP.get_pricelist2 (CUSTOMER_INFO.CUSTOMER_ID) AS PRICELIST2,
            IFSAPP.get_pricelist3 (CUSTOMER_INFO.CUSTOMER_ID) AS PRICELIST3,
            IFSAPP.get_pricelist4 (CUSTOMER_INFO.CUSTOMER_ID) AS PRICELIST4,
            IFSAPP.get_pricelist5 (CUSTOMER_INFO.CUSTOMER_ID) AS PRICELIST5,
            CUSTOMER_CREDIT_INFO_CUST.CREDIT_LIMIT,
            CUSTOMER_CREDIT_INFO_CUST.CREDIT_BLOCK,
            IDENTITY_INVOICE_INFO.INVOICE_FEE,
            IDENTITY_INVOICE_INFO.COMPANY,
            IDENTITY_INVOICE_INFO.PAY_TERM_ID,
            IFSAPP.Payment_Term_API.Get_Description (
               IDENTITY_INVOICE_INFO.COMPANY,
               IDENTITY_INVOICE_INFO.PAY_TERM_ID)
               AS PAYMENT_TERM_DESCRIPTION,
            CUST_ORD_CUSTOMER_ENT.CUST_PRICE_GROUP_ID,
            DECODE (Subquery.MAX_AGREEMENT, NULL, 'NO', 'YES') AS AGREEMENT_YN,
            CUST_ORD_CUSTOMER_ENT.DATE_DEL AS EXPIRE_DATE,
            IFSAPP.PERSON_INFO_API.GET_NAMe (CUST_ORD_CUSTOMER.SALESMAN_CODE)
               AS SALESPERSON_NAME,
            CUSTOMER_INFO_ADDRESS.ADDRESS1 AS ADDRESS1,
            CUSTOMER_INFO_ADDRESS.ADDRESS2 AS ADDRESS2,
            CUSTOMER_INFO_ADDRESS.CITY AS CITY,
            CUSTOMER_INFO_ADDRESS.STATE AS STATE,
            CUSTOMER_INFO_ADDRESS.ZIP_CODE AS ZIP_CODE
       FROM ((((((((((IFSAPP.CUSTOMER_INFO CUSTOMER_INFO
                      INNER JOIN
                      IFSAPP.CUST_ORD_CUSTOMER_ADDRESS_ENT CUST_ORD_CUSTOMER_ADDRESS_ENT
                         ON (CUSTOMER_INFO.CUSTOMER_ID =
                                CUST_ORD_CUSTOMER_ADDRESS_ENT.CUSTOMER_ID))
                     LEFT OUTER JOIN
                     IFSAPP.CUSTOMER_INFO_ADDRESS CUSTOMER_INFO_ADDRESS
                        ON (CUSTOMER_INFO.CUSTOMER_ID =
                               CUSTOMER_INFO_ADDRESS.CUSTOMER_ID))
                    LEFT OUTER JOIN
                    IFSAPP.CUSTOMER_INFO_COMM_METHOD CUSTOMER_INFO_COMM_METHOD
                       ON (CUSTOMER_INFO.CUSTOMER_ID =
                              CUSTOMER_INFO_COMM_METHOD.CUSTOMER_ID))
                   LEFT OUTER JOIN
                   IFSAPP.PARTY_TYPE_ID_PROPERTY PARTY_TYPE_ID_PROPERTY
                      ON (CUSTOMER_INFO.CUSTOMER_ID =
                             PARTY_TYPE_ID_PROPERTY.IDENTITY))
                  LEFT OUTER JOIN IFSAPP.VMO_COMPANY VMO_COMPANY
                     ON (CUSTOMER_INFO.CUSTOMER_ID = VMO_COMPANY.CUSTNO))
                 LEFT OUTER JOIN IFSAPP.CUST_ORD_CUSTOMER CUST_ORD_CUSTOMER
                    ON (CUSTOMER_INFO.CUSTOMER_ID =
                           CUST_ORD_CUSTOMER.CUSTOMER_NO))
                LEFT OUTER JOIN
                IFSAPP.CUSTOMER_CREDIT_INFO_CUST CUSTOMER_CREDIT_INFO_CUST
                   ON (CUSTOMER_INFO.CUSTOMER_ID =
                          CUSTOMER_CREDIT_INFO_CUST.IDENTITY))
               LEFT OUTER JOIN
               IFSAPP.IDENTITY_INVOICE_INFO IDENTITY_INVOICE_INFO
                  ON (CUSTOMER_INFO.CUSTOMER_ID =
                         IDENTITY_INVOICE_INFO.IDENTITY))
              LEFT OUTER JOIN
              IFSAPP.CUSTOMER_INFO_COMM_METHOD CUSTOMER_INFO_COMM_METHOD_1
                 ON (CUSTOMER_INFO.CUSTOMER_ID =
                        CUSTOMER_INFO_COMM_METHOD_1.CUSTOMER_ID))
             LEFT OUTER JOIN IFSAPP.CUST_ORD_CUSTOMER_ENT CUST_ORD_CUSTOMER_ENT
                ON (CUSTOMER_INFO.CUSTOMER_ID =
                       CUST_ORD_CUSTOMER_ENT.CUSTOMER_ID))
            LEFT OUTER JOIN
            (  SELECT CUSTOMER_AGREEMENT.CUSTOMER_NO,
                      MAX (CUSTOMER_AGREEMENT.AGREEMENT_ID) AS MAX_AGREEMENT
                 FROM IFSAPP.CUSTOMER_AGREEMENT CUSTOMER_AGREEMENT
                WHERE (    "CUSTOMER_AGREEMENT"."VALID_UNTIL" IS NOT NULL
                       AND "CUSTOMER_AGREEMENT"."VALID_UNTIL" >= SYSDATE)
             GROUP BY CUSTOMER_AGREEMENT.CUSTOMER_NO
             ORDER BY CUSTOMER_AGREEMENT.CUSTOMER_NO ASC) Subquery
               ON (CUSTOMER_INFO.CUSTOMER_ID = Subquery.CUSTOMER_NO)
      WHERE     (CUST_ORD_CUSTOMER_ADDRESS_ENT.ADDRESS_ID = '01')
            AND (PARTY_TYPE_ID_PROPERTY.COMPANY IN ('11', '21', '31'))
            AND (CUSTOMER_INFO_ADDRESS.ADDRESS_ID = '01')
            AND (CUSTOMER_INFO_COMM_METHOD.COMM_ID = 1)
            AND (CUSTOMER_INFO_COMM_METHOD_1.COMM_ID = 2)
            AND (IDENTITY_INVOICE_INFO.COMPANY IN ('11', '21', '31'))
            AND (CUST_ORD_CUSTOMER_ENT.DATE_DEL >=
                    TO_DATE (
                       '1/1/' || TO_CHAR (EXTRACT (YEAR FROM SYSDATE) - 1),
                       'mm/dd/yyyy'))
            AND (IDENTITY_INVOICE_INFO.PARTY_TYPE_DB = 'CUSTOMER')
            and customer_info.CUSTOMER_ID = 'COR001'
   ORDER BY CUSTOMER_INFO.CUSTOMER_ID ASC