     SELECT    TO_CHAR (CUSTOMER_ORDER_INV_HEAD.INVOICE_DATE, 'YYYYMMDD')
            || CUSTOMER_ORDER_INV_HEAD.IDENTITY
            || CUSTOMER_ORDER_INV_ITEM.CATALOG_NO
               AS "KEY",
            CUSTOMER_ORDER_INV_HEAD.COMPANY,
            CUSTOMER_ORDER_INV_HEAD.IDENTITY,
            TO_CHAR (TRUNC (CUSTOMER_ORDER_INV_HEAD.INVOICE_DATE), 'yyyymmdd')
               AS INVOICE_DATE,
            CUSTOMER_ORDER_INV_ITEM.CATALOG_NO,
            SUM (CUSTOMER_ORDER_INV_ITEM.INVOICED_QTY) AS SUM_INVOICED_QTY,
            CUSTOMER_ORDER_INV_ITEM.NET_DOM_AMOUNT 
               AS EXTENDED_SALE
       FROM IFSAPP.CUSTOMER_ORDER_INV_HEAD CUSTOMER_ORDER_INV_HEAD
            LEFT OUTER JOIN
            IFSAPP.CUSTOMER_ORDER_INV_ITEM CUSTOMER_ORDER_INV_ITEM
               ON (CUSTOMER_ORDER_INV_HEAD.INVOICE_ID =
                      CUSTOMER_ORDER_INV_ITEM.INVOICE_ID)
      WHERE     (CUSTOMER_ORDER_INV_HEAD.COMPANY IN ('11', '21', '31'))
            AND (CUSTOMER_ORDER_INV_HEAD.INVOICE_DATE >=
                    TO_DATE (
                       '1/1/' || TO_CHAR (EXTRACT (YEAR FROM SYSDATE) - 1),
                       'mm/dd/yyyy'))
            AND (CUSTOMER_ORDER_INV_HEAD.OBJSTATE != 'Preliminary')
            and CUSTOMER_ORDER_INV_HEAD.identity = '042750'
   GROUP BY    TO_CHAR (CUSTOMER_ORDER_INV_HEAD.INVOICE_DATE, 'YYYYMMDD')
            || CUSTOMER_ORDER_INV_HEAD.IDENTITY
            || CUSTOMER_ORDER_INV_ITEM.CATALOG_NO,
            CUSTOMER_ORDER_INV_HEAD.COMPANY,
            CUSTOMER_ORDER_INV_HEAD.IDENTITY,
            TO_CHAR (TRUNC (CUSTOMER_ORDER_INV_HEAD.INVOICE_DATE),
                     'yyyymmdd'),
            CUSTOMER_ORDER_INV_ITEM.CATALOG_NO,
            CUSTOMER_ORDER_INV_ITEM.NET_DOM_AMOUNT
   ORDER BY 1 ASC