USE [EDI_PTM]
GO

/****** Object:  Index [EI_HISTDTLWFIDNAMEVALUE_IDX]    Script Date: 9/30/2020 8:26:33 AM ******/
DROP INDEX [EI_HISTDTLWFIDTIDNAMEVALUE_IDX] ON [dbo].[EI_HISTORY_TRANDTL]
GO
            

/*Ran in EDI_TEST on 9-30-2020*/--EI_HISTDTLWFIDNAMEVALUE_IDX


commit;