CREATE TABLESPACE ver_tps9 DATAFILE 'C:\ORADATA\REPT\fnd_vertps9.dbf' SIZE 2400M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_gis9 DATAFILE 'C:\ORADATA\REPT\fnd_vergis.dbf9' SIZE 1200M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_utl9 DATAFILE 'C:\ORADATA\REPT\fnd_verutl.dbf9' SIZE 25M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_jrl9 DATAFILE 'C:\ORADATA\REPT\fnd_verjrl9.dbf' SIZE 1500M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_rpt9 DATAFILE 'C:\ORADATA\REPT\fnd_verrpt.dbf9' SIZE 3100M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;