CREATE TABLESPACE ver_tps DATAFILE 'D:\ORADATA\REP2\fnd_vertps.dbf' SIZE 2400M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE USER VERTPS IDENTIFIED BY INTERNAL DEFAULT TABLESPACE ver_tps
TEMPORARY TABLESPACE TMPHOLD2;

CREATE TABLESPACE ver_gis DATAFILE 'C:\ORADATA\REPT\fnd_vergis.dbf' SIZE 1200M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE USER VERGIS IDENTIFIED BY INTERNAL DEFAULT TABLESPACE ver_gis
TEMPORARY TABLESPACE TMPHOLD2;

CREATE TABLESPACE ver_utl DATAFILE 'C:\ORADATA\REPT\fnd_verutl.dbf' SIZE 25M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE USER VERUTL IDENTIFIED BY INTERNAL DEFAULT TABLESPACE ver_utl
TEMPORARY TABLESPACE TMPHOLD2;

CREATE TABLESPACE ver_jrl DATAFILE 'C:\ORADATA\REPT\fnd_verjrl.dbf' SIZE 1500M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE USER VERJRL IDENTIFIED BY INTERNAL DEFAULT TABLESPACE ver_jrl
TEMPORARY TABLESPACE TMPHOLD2;

CREATE TABLESPACE ver_rpt DATAFILE 'C:\ORADATA\REPT\fnd_verrpt.dbf' SIZE 3100M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE USER VERRPT IDENTIFIED BY INTERNAL DEFAULT TABLESPACE ver_rpt
TEMPORARY TABLESPACE TMPHOLD2;

CREATE ROLE VERTEX NOT IDENTIFIED;

