--Creates users for Vertex Project and assignes required access
--VER_TPS, VER_GIS, VER_JRL, VER_RPT, VER_UTL
CREATE USER "VER_TPS" PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_TPS" 
QUOTA UNLIMITED 
ON "VER_TPS" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_TPS";
GRANT CREATE ANY TABLE TO "VER_TPS";
GRANT CREATE ANY OBJECT TO "VER_TPS";
GRANT CREATE ANY VIEW TO "VER_TPS";
GRANT DROP ANY VIEW TO "VER_TPS";
GRANT CREATE ANY SEQUENCE TO "VER_TPS";
GRANT CREATE ANY TRIGGER TO "VER_TPS";
GRANT SELECT ANY TABLE TO "VER_TPS";
GRANT CONNECT TO "VER_TPS";

CREATE USER "VER_GIS" PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_GIS" 
QUOTA UNLIMITED 
ON "VER_GIS" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_GIS";
GRANT CREATE ANY TABLE TO "VER_GIS";
GRANT CREATE ANY OBJECT TO "VER_GIS";
GRANT CREATE ANY VIEW TO "VER_GIS";
GRANT DROP ANY VIEW TO "VER_GIS";
GRANT CREATE ANY SEQUENCE TO "VER_GIS";
GRANT CREATE ANY TRIGGER TO "VER_GIS";
GRANT SELECT ANY TABLE TO "VER_GIS";
GRANT CONNECT TO "VER_GIS";

CREATE USER "VER_JRL" PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_JRL" 
QUOTA UNLIMITED 
ON "VER_JRL" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_JRL";
GRANT CREATE ANY TABLE TO "VER_JRL";
GRANT CREATE ANY OBJECT TO "VER_JRL";
GRANT CREATE ANY VIEW TO "VER_JRL";
GRANT DROP ANY VIEW TO "VER_JRL";
GRANT CREATE ANY SEQUENCE TO "VER_JRL";
GRANT CREATE ANY TRIGGER TO "VER_JRL";
GRANT SELECT ANY TABLE TO "VER_JRL";
GRANT CONNECT TO "VER_JRL";

CREATE USER "VER_RPT" PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_RPT" 
QUOTA UNLIMITED 
ON "VER_RPT" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_RPT";
GRANT CREATE ANY TABLE TO "VER_RPT";
GRANT CREATE ANY OBJECT TO "VER_RPT";
GRANT CREATE ANY VIEW TO "VER_RPT";
GRANT DROP ANY VIEW TO "VER_RPT";
GRANT CREATE ANY SEQUENCE TO "VER_RPT";
GRANT CREATE ANY TRIGGER TO "VER_RPT";
GRANT SELECT ANY TABLE TO "VER_RPT";
GRANT CONNECT TO "VER_RPT";

CREATE USER "VER_UTL" PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_UTL" 
QUOTA UNLIMITED 
ON "VER_UTL" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_UTL";
GRANT CREATE ANY TABLE TO "VER_UTL";
GRANT CREATE ANY OBJECT TO "VER_UTL";
GRANT CREATE ANY VIEW TO "VER_UTL";
GRANT DROP ANY VIEW TO "VER_UTL";
GRANT CREATE ANY SEQUENCE TO "VER_UTL";
GRANT CREATE ANY TRIGGER TO "VER_UTL";
GRANT SELECT ANY TABLE TO "VER_UTL";
GRANT CONNECT TO "VER_UTL";

