CREATE TABLESPACE ver_tps9 DATAFILE 'C:\ORADATA\REPT\fnd_vertps9.dbf' SIZE 2400M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_gis9 DATAFILE 'C:\ORADATA\REPT\fnd_vergis.dbf9' SIZE 1200M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_utl9 DATAFILE 'C:\ORADATA\REPT\fnd_verutl.dbf9' SIZE 25M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_jrl9 DATAFILE 'C:\ORADATA\REPT\fnd_verjrl9.dbf' SIZE 1500M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_rpt9 DATAFILE 'C:\ORADATA\REPT\fnd_verrpt.dbf9' SIZE 3100M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

--Creates users for Vertex Project and assignes required access
--VER_TPS, VER_GIS, VER_JRL, VER_RPT, VER_UTL
CREATE USER "VER_TPS9" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_TPS9" 
QUOTA UNLIMITED 
ON "VER_TPS9" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_TPS9";
GRANT CREATE ANY TABLE TO "VER_TPS9";
--GRANT CREATE ANY OBJECT TO "VER_TPS9";
GRANT CREATE ANY VIEW TO "VER_TPS9";
GRANT DROP ANY VIEW TO "VER_TPS9";
GRANT CREATE ANY SEQUENCE TO "VER_TPS9";
GRANT CREATE ANY TRIGGER TO "VER_TPS9";
GRANT SELECT ANY TABLE TO "VER_TPS9";
GRANT CONNECT TO "VER_TPS9";

CREATE USER "VER_GIS9" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_GIS9" 
QUOTA UNLIMITED 
ON "VER_GIS9" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_GIS9";
GRANT CREATE ANY TABLE TO "VER_GIS9";
--GRANT CREATE ANY OBJECT TO "VER_GIS9";
GRANT CREATE ANY VIEW TO "VER_GIS9";
GRANT DROP ANY VIEW TO "VER_GIS9";
GRANT CREATE ANY SEQUENCE TO "VER_GIS9";
GRANT CREATE ANY TRIGGER TO "VER_GIS9";
GRANT SELECT ANY TABLE TO "VER_GIS9";
GRANT CONNECT TO "VER_GIS9";

CREATE USER "VER_JRL9" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_JRL9" 
QUOTA UNLIMITED 
ON "VER_JRL9" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_JRL9";
GRANT CREATE ANY TABLE TO "VER_JRL9";
--GRANT CREATE ANY OBJECT TO "VER_JRL9";
GRANT CREATE ANY VIEW TO "VER_JRL9";
GRANT DROP ANY VIEW TO "VER_JRL9";
GRANT CREATE ANY SEQUENCE TO "VER_JRL9";
GRANT CREATE ANY TRIGGER TO "VER_JRL9";
GRANT SELECT ANY TABLE TO "VER_JRL9";
GRANT CONNECT TO "VER_JRL9";

CREATE USER "VER_RPT9" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_RPT9" 
QUOTA UNLIMITED 
ON "VER_RPT9" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_RPT9";
GRANT CREATE ANY TABLE TO "VER_RPT9";
--GRANT CREATE ANY OBJECT TO "VER_RPT9";
GRANT CREATE ANY VIEW TO "VER_RPT9";
GRANT DROP ANY VIEW TO "VER_RPT9";
GRANT CREATE ANY SEQUENCE TO "VER_RPT9";
GRANT CREATE ANY TRIGGER TO "VER_RPT9";
GRANT SELECT ANY TABLE TO "VER_RPT9";
GRANT CONNECT TO "VER_RPT9";

CREATE USER "VER_UTL9" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_UTL9" 
QUOTA UNLIMITED 
ON "VER_UTL9" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_UTL9";
GRANT CREATE ANY TABLE TO "VER_UTL9";
--GRANT CREATE ANY OBJECT TO "VER_UTL9";
GRANT CREATE ANY VIEW TO "VER_UTL9";
GRANT DROP ANY VIEW TO "VER_UTL9";
GRANT CREATE ANY SEQUENCE TO "VER_UTL9";
GRANT CREATE ANY TRIGGER TO "VER_UTL9";
GRANT SELECT ANY TABLE TO "VER_UTL9";
GRANT CONNECT TO "VER_UTL9";