CREATE TABLESPACE ver_tps91 DATAFILE 'C:\ORADATA\CRP\fnd_vertps91.dbf' SIZE 2400M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_gis91 DATAFILE 'C:\ORADATA\CRP\fnd_vergis91.dbf' SIZE 1200M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_utl91 DATAFILE 'C:\ORADATA\CRP\fnd_verutl91.dbf' SIZE 25M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_jrl91 DATAFILE 'C:\ORADATA\CRP\fnd_verjrl91.dbf' SIZE 1500M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_rpt91 DATAFILE 'C:\ORADATA\CRP\fnd_verrpt91.dbf' SIZE 3100M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

--Creates users for Vertex Project and assignes required access
--VER_TPS, VER_GIS, VER_JRL, VER_RPT, VER_UTL
CREATE USER "VER_TPS91" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_TPS91" 
QUOTA UNLIMITED 
ON "VER_TPS91" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_TPS91";
GRANT CREATE ANY TABLE TO "VER_TPS91";
--GRANT CREATE ANY OBJECT TO "VER_TPS9";
GRANT CREATE ANY VIEW TO "VER_TPS91";
GRANT DROP ANY VIEW TO "VER_TPS91";
GRANT CREATE ANY SEQUENCE TO "VER_TPS91";
GRANT CREATE ANY TRIGGER TO "VER_TPS91";
GRANT SELECT ANY TABLE TO "VER_TPS91";
GRANT CONNECT TO "VER_TPS91";

CREATE USER "VER_GIS91" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_GIS91" 
QUOTA UNLIMITED 
ON "VER_GIS91" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_GIS91";
GRANT CREATE ANY TABLE TO "VER_GIS91";
--GRANT CREATE ANY OBJECT TO "VER_GIS9";
GRANT CREATE ANY VIEW TO "VER_GIS91";
GRANT DROP ANY VIEW TO "VER_GIS91";
GRANT CREATE ANY SEQUENCE TO "VER_GIS91";
GRANT CREATE ANY TRIGGER TO "VER_GIS91";
GRANT SELECT ANY TABLE TO "VER_GIS91";
GRANT CONNECT TO "VER_GIS91";

CREATE USER "VER_JRL91" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_JRL91" 
QUOTA UNLIMITED 
ON "VER_JRL91" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_JRL91";
GRANT CREATE ANY TABLE TO "VER_JRL91";
--GRANT CREATE ANY OBJECT TO "VER_JRL9";
GRANT CREATE ANY VIEW TO "VER_JRL91";
GRANT DROP ANY VIEW TO "VER_JRL91";
GRANT CREATE ANY SEQUENCE TO "VER_JRL91";
GRANT CREATE ANY TRIGGER TO "VER_JRL91";
GRANT SELECT ANY TABLE TO "VER_JRL91";
GRANT CONNECT TO "VER_JRL91";

CREATE USER "VER_RPT91" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_RPT91" 
QUOTA UNLIMITED 
ON "VER_RPT91" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_RPT91";
GRANT CREATE ANY TABLE TO "VER_RPT91";
--GRANT CREATE ANY OBJECT TO "VER_RPT9";
GRANT CREATE ANY VIEW TO "VER_RPT91";
GRANT DROP ANY VIEW TO "VER_RPT91";
GRANT CREATE ANY SEQUENCE TO "VER_RPT91";
GRANT CREATE ANY TRIGGER TO "VER_RPT91";
GRANT SELECT ANY TABLE TO "VER_RPT91";
GRANT CONNECT TO "VER_RPT91";

CREATE USER "VER_UTL91" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_UTL91" 
QUOTA UNLIMITED 
ON "VER_UTL91" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_UTL91";
GRANT CREATE ANY TABLE TO "VER_UTL91";
--GRANT CREATE ANY OBJECT TO "VER_UTL9";
GRANT CREATE ANY VIEW TO "VER_UTL91";
GRANT DROP ANY VIEW TO "VER_UTL91";
GRANT CREATE ANY SEQUENCE TO "VER_UTL91";
GRANT CREATE ANY TRIGGER TO "VER_UTL91";
GRANT SELECT ANY TABLE TO "VER_UTL91";
GRANT CONNECT TO "VER_UTL91";