DECLARE
    in_part_no varchar2;
	CURSOR OBS_INVENTORY_LIST IS
	    select DISTINCT A.CONTRACT, A.TOP_LEVEL_PART_NO, A.PART_NO, B.TOP_LEVEL_PART_NO COMP_TOP_LVL_PART
        , C.PART_STATUS COMP_PART_STATUS, C.ACCOUNTING_GROUP COMP_ACCOUNTING_GROUP_CODE
        from ifsapp.part_cost_bucket A, ifsapp.part_cost_bucket b, IFSAPP.INVENTORY_PART C
        where 
        B.CONTRACT = A.CONTRACT AND B.PART_NO = A.PART_NO AND
        B.COST_SET = A.COST_SET AND B.COST_BUCKET_ID = A.COST_BUCKET_ID AND
        C.PART_NO = B.TOP_LEVEL_PART_NO AND C.CONTRACT = B.CONTRACT AND
        A.top_level_part_NO IN (&OBS_INVENTORY) AND
        C.PART_STATUS <> 'O' AND C.ACCOUNTING_GROUP LIKE 'FG%' AND
        A.COST_BUCKET_ID = '110' AND A.COST_SET = 1;
    CURSOR INV_LOCATION IS
	 	   SELECT LOCATION_NO, QTY_RESERVED
		   FROM IFSAPP.INVENTORY_PART_IN_STOCK_TAB
		   WHERE PART_NO = in_part_no;
	v_prl_part PRL_PART_UPDATE%rowtype; 
	v_inv_location INV_LOCATION%rowtype;  	   
BEGIN
     DELETE FROM IFSINFO.PRL_INV_ADJ;
     OPEN PRL_PART_UPDATE;
	 LOOP
	 	 FETCH PRL_PART_UPDATE into v_prl_part;
		 	   exit when PRL_PART_UPDATE%notfound;
	     in_part_no := v_prl_part.INVENTORY_PART_NUMBER;
		 OPEN INV_LOCATION;
		 LOOP
		 	 FETCH INV_LOCATION INTO v_inv_location;
			   exit when INV_LOCATION%notfound;
			   INSERT INTO IFSINFO.PRL_INV_ADJ(INVENTORY_PART_NUMBER, PART_LOCATION, QTY_RESERVED, ADJUST, USERNAME)
		 		VALUES(v_prl_part.INVENTORY_PART_NUMBER, v_inv_location.LOCATION_NO, v_inv_location.QTY_RESERVED ,'N',USER);
		 END LOOP;
	 	 CLOSE INV_LOCATION; 
	 END LOOP;
	 CLOSE PRL_PART_UPDATE;
	 COMMIT;
END;
END;   -- END OF CREATE PROCEDURE 
