create or replace procedure INVENTORY_REPORTLOCATIONS as  -- UNCOMMENT TO CREATE PROCEDURE FOR JOB, AND END AT BOTTOM 
begin
DECLARE
    in_part_no varchar2(25);
	CURSOR PRL_PART_UPDATE IS
	       SELECT INVENTORY_PART_NUMBER
		   FROM IFSINFO.PRL_PART_REVIEW
		   WHERE CORRECTED = 'N' AND IGNORED = 'N';
    CURSOR INV_LOCATION IS
	 	   SELECT LOCATION_NO, QTY_RESERVED
		   FROM IFSAPP.INVENTORY_PART_IN_STOCK_TAB
		   WHERE PART_NO = in_part_no;
	v_prl_part PRL_PART_UPDATE%rowtype; 
	v_inv_location INV_LOCATION%rowtype;  	   
BEGIN
     DELETE FROM IFSINFO.PRL_INV_ADJ;
     OPEN PRL_PART_UPDATE;
	 LOOP
	 	 FETCH PRL_PART_UPDATE into v_prl_part;
		 	   exit when PRL_PART_UPDATE%notfound;
	     in_part_no := v_prl_part.INVENTORY_PART_NUMBER;
		 OPEN INV_LOCATION;
		 LOOP
		 	 FETCH INV_LOCATION INTO v_inv_location;
			   exit when INV_LOCATION%notfound;
			   INSERT INTO IFSINFO.PRL_INV_ADJ(INVENTORY_PART_NUMBER, PART_LOCATION, QTY_RESERVED, ADJUST, USERNAME)
		 		VALUES(v_prl_part.INVENTORY_PART_NUMBER, v_inv_location.LOCATION_NO, v_inv_location.QTY_RESERVED ,'N',USER);
		 END LOOP;
	 	 CLOSE INV_LOCATION; 
	 END LOOP;
	 CLOSE PRL_PART_UPDATE;
	 COMMIT;
END;
END;   -- END OF CREATE PROCEDURE 
