update ifsapp.inventory_part_in_stock_tab
set qty_reserved = 0 where part_no = 'JM2650DS'
and location_no = 'S1A202';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '983-0020'
AND LOCATION_NO = 'FP004';

/*
UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '055-KPJF-S-1'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '055-KPRS-W'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '055-KSP9-B'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '095-KLCL-1'
AND LOCATION_NO = 'S1Q109';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '095-KLCL-1'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '095-KLCS-1'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '095-KLPL-1'
AND LOCATION_NO = 'TEMP1';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = '095-KRTLPL-1'
AND LOCATION_NO = 'TEMP1';
/*
UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

UPDATE IFSAPP.INVENTORY_PART_IN_STOCK_TAB
SET QTY_RESERVED = 0 WHERE PART_NO = ''
AND LOCATION_NO = '';

*/

COMMIT
--ROLLBACK
