select customer_name, catalog_no, period_year, sum(curr_line_total) CY_TOTAL, SUM(LY_LINE_TOTAL) LY_TOTAL
FROM(
SELECT ORDER_NO, CUSTOMER_NAME, LINE_NO, CATALOG_NO, TRUNC(DATE_ENTERED, 'DD') DATE_ENTERED, REVISED_QTY_DUE, SALE_UNIT_PRICE, TO_CHAR(DATE_ENTERED, 'MMYYYY') PERIOD_YEAR,
null curr_line_total, (SALE_UNIT_PRICE * REVISED_QTY_DUE) ly_LINE_TOTAL
FROM IFSINFO.CUST_ORDLINE_INFO WHERE CONTRACT = 'MP' and date_entered between to_date('1/1/2014','mm/dd/yyyy') and to_date('12/31/2014','mm/dd/yyyy')
UNION
SELECT ORDER_NO, CUSTOMER_NAME, LINE_NO, CATALOG_NO, TO_DATE(CANCELDATE, 'YYYYMMDD') DATE_ENTERED, REVISED_QTY_DUE, SALE_UNIT_PRICE, TO_CHAR(TO_DATE(CANCELDATE, 'YYYYMMDD'), 'MMYYYY') PERIOD_YEAR, 
null curr_line_total, ((SALE_UNIT_PRICE * -1) * REVISED_QTY_DUE) ly_LINE_TOTAL
FROM IFSINFO.CUST_ORDLINE_INFOB where to_date(canceldate, 'yyyymmdd') between to_date('1/1/2014','mm/dd/yyyy') and to_date('12/31/2014','mm/dd/yyyy')
union
SELECT ORDER_NO, CUSTOMER_NAME, LINE_NO, CATALOG_NO, TRUNC(DATE_ENTERED, 'DD') DATE_ENTERED, REVISED_QTY_DUE, SALE_UNIT_PRICE, TO_CHAR(DATE_ENTERED, 'MMYYYY') PERIOD_YEAR,
(SALE_UNIT_PRICE * REVISED_QTY_DUE) curr_line_total, null ly_LINE_TOTAL
FROM IFSINFO.CUST_ORDLINE_INFO WHERE CONTRACT = 'MP' and date_entered between to_date('1/1/2015','mm/dd/yyyy') and to_date('12/31/2015','mm/dd/yyyy')
UNION
SELECT ORDER_NO, CUSTOMER_NAME, LINE_NO, CATALOG_NO, TO_DATE(CANCELDATE, 'YYYYMMDD') DATE_ENTERED, REVISED_QTY_DUE, SALE_UNIT_PRICE, TO_CHAR(TO_DATE(CANCELDATE, 'YYYYMMDD'), 'MMYYYY') PERIOD_YEAR, 
((SALE_UNIT_PRICE * -1) * REVISED_QTY_DUE) curr_line_total, null ly_LINE_TOTAL
FROM IFSINFO.CUST_ORDLINE_INFOB where to_date(canceldate, 'yyyymmdd') between to_date('1/1/2015','mm/dd/yyyy') and to_date('12/31/2015','mm/dd/yyyy')
)
GROUP BY CUSTOMER_NAME, CATALOG_NO, PERIOD_YEAR