--RAN ON 12/04 TO GENERATE SUPPLIER LIST FOR DOUG TO AUDIT IFS ENTRIES

SELECT A.SUPPLIER_ID, A.NAME, A.CREATION_DATE, B.GROUP_ID SUPPLIER_GROUP, 
B.DEF_AUTHORIZER, B.AUTO_AUTH_FINAL_ENTRY, B.PAY_TERM_ID, B.DEF_VAT_CODE, B.DEF_CURRENCY, B.VAT_NO, B.TAX_REGIME, B.LIABILITY_TYPE TAX_LIABILITY,
IFSAPP.PAYMENT_WAY_PER_IDENTITY_API.GET_DEFAULT_PAYMENT_WAY('31',A.SUPPLIER_ID,'Supplier') PAYMENT_METHOD,
C.ADDRESS_ID, C.ADDRESS1, C.ADDRESS2, C.ZIP_CODE, C.CITY,  C.STATE, D.METHOD_DEFAULT, D.ADDRESS_DEFAULT, D.DOCUMENT_RECEIVER, D.ADDRESS_ID, B.COMPANY INVOICE_COMPANY, E.COMPANY PAYMENT_COMPANY        
FROM SUPPLIER_INFO A, IDENTITY_INVOICE_INFO B, SUPPLIER_INFO_ADDRESS C, SUPPLIER_INFO_COMM_METHOD D, IDENTITY_PAY_INFO E
WHERE 
A.SUPPLIER_ID = B.IDENTITY AND 
A.SUPPLIER_ID = C.SUPPLIER_ID
AND A.SUPPLIER_ID = E.IDENTITY
AND E.PARTY_TYPE_DB = 'SUPPLIER'
AND A.SUPPLIER_ID = D.SUPPLIER_ID AND
A.SUPPLIER_ID LIKE 'B%' AND
D.COMM_ID = 1
ORDER BY NAME




select * from supplier_info_address where supplier_id like 'B%'


SELECT * FROM PAYMENT_WAY_PER_IDENTITY WHERE IDENTITY LIKE 'B%'


SELECT IFSAPP.PAYMENT_WAY_PER_IDENTITY_API.GET_DEFAULT_PAYMENT_WAY('31','B030007','Supplier') FROM DUAL

SELECT * FROM SUPPLIER_INFO_COMM_METHOD


SELECT * FROM IDENTITY_PAY_INFO