SELECT MPS_GET_CURRENT_DAY('CMJ500'), MPS_GET_DEMAND_DATE('CMJ500'),
MPS_GET_PLANNING_DATE('CMJ500'), mps_get_current_counter('CMJ500'), MPS_GET_DEM_COUNTER('CMJ500'),
MPS_GET_PLN_COUNTER('CMJ500')
 FROM DUAL