select * from ifsapp.inventory_part_config_all
where planner_buyer = 'FG_CHINA'

SELECT ORDER_NO, LINE_NO, RELEASE_NO, PART_NO, BUY_QTY_DUE, DATE_ENTERED, PLANNED_DELIVERY_DATE, PLANNED_RECEIPT_DATE,  STATE

SELECT *
FROM PURCHASE_ORDER_LINE_PART WHERE PART_NO = 'LMAM1940'
AND upper(STATE) IN ('RELEASED','CONFIRMED','ARRIVED','PLANNED')



SELECT ifsapp.LEVEL_1_PART.PART_NO, ifsapp.ORDER_SUPPLY_DEMAND_EXT.CONTRACT, 
ifsapp.INVENTORY_PART_API.GET_PLANNER_BUYER(ifsapp.ORDER_SUPPLY_DEMAND_EXT.CONTRACT,ifsapp.ORDER_SUPPLY_DEMAND_EXT.PART_NO) PLANNER,
ifsapp.ORDER_SUPPLY_DEMAND_EXT.ORDER_SUPPLY_DEMAND_TYPE, 
ifsapp.ORDER_SUPPLY_DEMAND_EXT.ORDER_NO, 
ifsapp.ORDER_SUPPLY_DEMAND_EXT.LINE_NO, 
ifsapp.ORDER_SUPPLY_DEMAND_EXT.REL_NO, 
ifsapp.ORDER_SUPPLY_DEMAND_EXT.DATE_REQUIRED,
ifsapp.ORDER_SUPPLY_DEMAND_EXT.QTY_SUPPLY, 
ifsapp.ORDER_SUPPLY_DEMAND_EXT.QTY_DEMAND,
ifsapp.PURCHASE_ORDER_LINE_PART.PLANNED_DELIVERY_DATE,
ifsapp.PURCHASE_ORDER_LINE_PART.PLANNED_RECEIPT_DATE
FROM IFSAPP.LEVEL_1_PART JOIN
ifsapp.ORDER_SUPPLY_DEMAND_EXT ON IFSAPP.LEVEL_1_PART.PART_NO = IFSAPP.ORDER_SUPPLY_DEMAND_EXT.PART_NO 
LEFT JOIN ifsapp.PURCHASE_ORDER_LINE_PART
ON ifsapp.ORDER_SUPPLY_DEMAND_EXT.ORDER_NO = ifsapp.PURCHASE_ORDER_LINE_PART.ORDER_NO
AND ifsapp.ORDER_SUPPLY_DEMAND_EXT.PART_NO = ifsapp.PURCHASE_ORDER_LINE_PART.PART_NO
AND ifsapp.ORDER_SUPPLY_DEMAND_EXT.LINE_NO = ifsapp.PURCHASE_ORDER_LINE_PART.LINE_NO
AND ifsapp.ORDER_SUPPLY_DEMAND_EXT.REL_NO = ifsapp.PURCHASE_ORDER_LINE_PART.RELEASE_NO