SELECT TBL1.PART_NO, TRUNC(SYSDATE) AS CURRENT_DAY,
(SELECT MAX(TBL2.COUNTER) FROM &AO..LEVEL_1_FORECAST TBL2 WHERE TBL2.MS_DATE <= TRUNC(SYSDATE) AND TBL1.PART_NO = TBL2.PART_NO AND TBL1.CONTRACT = TBL2.CONTRACT AND TBL1.MS_SET = TBL2.MS_SET) AS CURRENT_COUNTER, 
&AO..LEVEL_1_PART_API.Get_Demand_Tf_Date(TBL1.CONTRACT, TBL1.PART_NO, TBL1.MS_SET) AS DEMAND_TF_DATE,
(SELECT MAX(TBL2.COUNTER) FROM &AO..LEVEL_1_FORECAST TBL2 WHERE TBL2.MS_DATE <= &AO..LEVEL_1_PART_API.Get_Demand_Tf_Date(TBL1.CONTRACT, TBL1.PART_NO, TBL1.MS_SET) AND TBL1.PART_NO = TBL2.PART_NO AND TBL1.CONTRACT = TBL2.CONTRACT AND TBL1.MS_SET = TBL2.MS_SET) AS DEM_COUNTER,
&AO..LEVEL_1_PART_API.GET_PLANNING_TF_DATE(TBL1.CONTRACT, TBL1.PART_NO, TBL1.MS_SET) AS PLANNING_TF_DATE,
(SELECT TBL2.COUNTER FROM &AO..LEVEL_1_FORECAST TBL2 WHERE TBL2.MS_DATE = &AO..LEVEL_1_PART_API.Get_PLANNING_Tf_Date(TBL1.CONTRACT, TBL1.PART_NO, TBL1.MS_SET) + 1 AND TBL1.PART_NO = TBL2.PART_NO AND TBL1.CONTRACT = TBL2.CONTRACT AND TBL1.MS_SET = TBL2.MS_SET) AS PLN_COUNTER
FROM &AO..LEVEL_1_FORECAST TBL1
GROUP BY TBL1.PART_NO, TBL1.CONTRACT, TBL1.MS_SET