DROP TABLE IFSINFO.PRL_INV_ADJ;

CREATE TABLE IFSINFO.PRL_INV_ADJ
(
INVENTORY_PART_NUMBER VARCHAR2(50),
PART_LOCATION VARCHAR2(35),
QTY_RESERVED NUMBER,
ADJUST CHAR(1) DEFAULT 'N',
USERNAME VARCHAR2(50),
SET_RESERVED_TO INTEGER
)
TABLESPACE IAL_DATA
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;
COMMIT;

GRANT ALL ON IFSINFO.PRL_INV_ADJ TO IFSAPP WITH GRANT OPTION;