SELECT A.ERR_DESCR, (SELECT ORDER_NO FROM IFSAPP.SHOP_ORD B WHERE b.part_no like   
FROM 
ACTIVE_WORK_ORDER A
WHERE ERR_DESCR LIKE 'ECN%'





UNION
SELECT ERR_DESCR
FROM
HISTORICAL_WORK_ORDER
WHERE ERR_DESCR LIKE 'ECN%'