--CREATE OR REPLACE VIEW EOL_TEST AS
SELECT CONTRACT SITE, PART_NO, IFSAPP.EOL_GET_CURRENT_POUT_DATE(PART_NO, CONTRACT)  PHASE_OUT_DATE,
IFSAPP.get_qty_onhand_all_loc(CONTRACT, PART_NO)  ON_HAND_QTY,
NVL(IFSAPP.EOL_GET_SHOP_ORD_PROP(PART_NO,CONTRACT),0) EOL_PLANNED,
NVL(IFSAPP.EOL_GET_SHOP_ORD_WIP(PART_NO,CONTRACT),0) EOL_WIP,
NVL(IFSAPP.ORDER_SUPPLY_DEMAND_API.GET_SUM_QTY_DEMAND(CONTRACT,PART_NO),0) OPEN_CUSTOMER_DEMAND,
round(NVL(IFSAPP.EOL_3_MONTH_AVG(PART_NO), 0),2) AVG_3_MONTHS
FROM IFSAPP.INVENTORY_PART
WHERE CONTRACT = '&SITE'
AND PLANNER_BUYER = '&PLANNER'










SELECT EOL_3_MONTH_AVG('PM20') FROM DUAL


SELECT EOL_GET_CURRENT_POUT_DATE('009-8021','MP') FROM DUAL
select get_qty_onhand_all_loc('MP','PM20') from dual



SELECT * FROM SHOP_ORD WHERE UPPER(state) in ('STARTED','RELEASED')
--and order_no = 345782

SELECT NVL(EOL_GET_SHOP_ORD_PROP('PM20','MP'),0) AS SHOP_ORD_WIP FROM DUAL

SELECT * FROM SHOP_ORDER_PROP where PART_NO = 'PLCT' AND STATE = 'ProposalCreated'

SELECT sum(DESIRED_QTY) FROM IFSAPP.CUSTOMER_ORDER_JOIN WHERE PART_NO = 'PLCT'
AND LINE_STATE IN ('Planned','Released','Reserved') and state in('Planned','Released','Reserved')

SELECT IFSAPP.ORDER_SUPPLY_DEMAND_API.GET_SUM_QTY_DEMAND('MP','JM2650') FROM DUAL

SELECT sum(QTY)/3
FROM IFSINFO.PRL_GROSS_PRFT_MPS
WHERE PART = 'PM20' 
AND CONTRACT = 'MP'
AND TRUNC(INV_DATE, 'MM') BETWEEN TRUNC(ADD_MONTHS(SYSDATE, -3),'MM') AND TRUNC(ADD_MONTHS(SYSDATE, -1),'MM')