SELECT * FROM (
SELECT IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER('MP', PART_NO) PLANNER_CODE, PART_NO, IFSAPP.PURCHASE_PART_SUPPLIER_API.GET_PRIMARY_SUPPLIER_NO('MP', PART_NO) SUPPLIER_NO, IFSAPP.SUPPLIER_INFO_API.GET_NAME(IFSAPP.PURCHASE_PART_SUPPLIER_API.GET_PRIMARY_SUPPLIER_NO('MP', PART_NO)) SUPPLIER_NAME, PART_DESCRIPTION PLANNER_BUYER, MRP_MESSAGE_CONDITION, CREATE_DATE FROM IFSAPP.MRP_PART_ACTION_PER_SETUP)
WHERE PLANNER_CODE IN ('INT_COMP','INT_MPS','PURC_COMP','PURC_FG')
AND MRP_MESSAGE_CONDITION IN ('Supply is Past Due', 'Late Order')

