SELECT PART_NO AS I_PART_NO, LOCATION_NO AS I_LOC_NO, QTY_RESERVED AS I_RESERVED
FROM INVENTORY_PART_IN_STOCK_TAB
WHERE PART_NO in ('JM2650DS')
AND CONTRACT = 'MP'
AND QTY_RESERVED > 0
ORDER BY 1;

SELECT ORDER_NO, PART_NO, CONTRACT, LINE_ITEM_NO, QTY_ASSIGNED, STATE FROM SHOP_MATERIAL_ALLOC WHERE PART_NO 
IN ('JM2650DS')
AND QTY_ASSIGNED > 0;

SELECT * FROM PURCHASE_ORDER_LINE_COMP WHERE COMPONENT_PART in 
('JM2650DS')	