SELECT A.ORDER_NO, A.DATE_ENTERED,  A.SHIP_VIA_CODE, A.CUSTOMER_NO, C.CHARGE_AMOUNT, C.CHARGE_TYPE, Sum((B.QTY_INVOICED*B.SALE_UNIT_PRICE)-B.ADDITIONAL_DISCOUNT) AS INVOICE_TOTAL
FROM IFSAPP.CUSTOMER_ORDER A LEFT JOIN IFSAPP.CUSTOMER_ORDER_LINE B 
ON A.ORDER_NO = B.ORDER_NO 
LEFT JOIN IFSAPP.CUSTOMER_ORDER_CHARGE C 
ON A.ORDER_NO = C.ORDER_NO
WHERE A.DATE_ENTERED BETWEEN TO_DATE('%FROM_DATE','MM/DD/YYYY') And TO_DATE('%TO_DATE','MM/DD/YYYY')
and A.CUSTOMER_NO = '092247'
and charge_amount > 0
AND A.SHIP_VIA_CODE = 'UPS'
GROUP BY A.ORDER_NO, A.CUSTOMER_NO, A.SHIP_VIA_CODE, C.CHARGE_AMOUNT, C.CHARGE_TYPE, A.DATE_ENTERED --, D.MESSAGE_TEXT
ORDER BY C.CHARGE_TYPE DESC;
