select CATALOG_NO, 
IFSAPP.SALES_PART_API.Get_Catalog_Desc_For_Lang('MP',CATALOG_NO,'en') DESCR, 
IFSAPP.GET_INV_CHAR(CATALOG_NO,'MP','UPC') UPC, 
IFSAPP.GET_INV_CHAR(CATALOG_NO, 'MP','COLOR') COLOR
FROM &AO..SALES_PART_CHARACTERISTIC 
WHERE CHARACTERISTIC_CODE = 'TNAME' AND ATTR_VALUE = 'ICW'