GRANT EXECUTE ON MPS_GET_CURRENT_COUNTER TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_CURRENT_DAY TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_DEMAND_DATE TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_DEMAND_DAY TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_DEM_COUNTER TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_LST_COUNTER TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_NEXT_PLN_DATE TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_PLANNING_DATE TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_PLANNING_DAY TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_PLN_COUNTER TO REQUESTIONER;
GRANT EXECUTE ON MPS_GET_SUM_SUPPLY TO REQUESTIONER;
GRANT EXECUTE ON EOL_3_MONTH_AVG TO REQUESTIONER;
GRANT EXECUTE ON EOL_GET_CURRENT_PIN_DATE TO REQUESTIONER;
GRANT EXECUTE ON EOL_GET_CURRENT_POUT_DATE TO REQUESTIONER;
GRANT EXECUTE ON EOL_GET_SHOP_ORD_PROP TO REQUESTIONER;
GRANT EXECUTE ON EOL_GET_SHOP_ORD_WIP TO REQUESTIONER;
GRANT EXECUTE ON PRL_GET_DEMAND TO REQUESTIONER;

GRANT EXECUTE ON Tube_Cell_Get_Sum_Qty_Demand TO REQUESTIONER;

GRANT SELECT ON IFSINFO.PRODUCTION_SCHEDULE_2006 TO REQUESTIONER;
GRANT SELECT ON IFSINFO.PRODUCTION_SCHEDULE_2006_IAL TO REQUESTIONER;
--GRANT EXECUTE ON MPS_GET_DAYS_ONHAND TO REQUESTIONER;

GRANT SELECT ON IFSINFO.prl_labor_rpt_new TO REQUESTIONER;

GRANT EXECUTE ON get_total_labor_duration TO REQUESTIONER;

grant execute on get_total_labor_irupt to REQUESTIONER;

grant execute on get_total_labor_prod_qty to REQUESTIONER;

grant execute on get_total_scrap_qty to requestioner;

grant execute on time_pers_diary_result_api to costing;

grant select on ifsinfo.prod_sched_by_planner_ial to requestioner;

grant execute on mps_get_sum_qty_demand to requestioner;