select OP_ID, EMP_NO, PART_NO, ACCOUNT_DATE, WORK_CENTER_NO, ORDER_NO, 
TIME_PERS_DIARY_RESULT_API.GET_WAGE_HOURS(11, EMP_NO, '%', '%', '%', ACCOUNT_DATE, ACCOUNT_DATE) WORK_HOURS,
R_TOTAL_WORKING_DURATION_100, 
R_LUNCH_IRUPT,  
R_HOT_IRUPT, 
R_INSPECTION_IRUPT, 
R_PROTOTYPE_IRUPT, 
R_CLEANING_IRUPT, 
R_MAINTENANCE_IRUPT, 
R_MEETING_IRUPT, 
R_MOVING_IRUPT, 
R_REWORK_IRUPT, 
R_SETUP_RESET_IRUPT, 
R_TRAINING_IRUPT, 
R_PROD_QTY, 
R_DAMAGAED_SCRAP + 
R_SETUP_SCRAP + 
R_OPERATOR_SCRAP + 
R_MACHINE_SCRAP + 
R_OBSOLETE_SCRAP + 
R_RETURN_SCRAP + 
R_REGULAR_SCRAP + 
R_RUSTED_SCRAP + 
R_DESIGN_SCRAP + 
R_OUTSIDE_PROCESS_SCRAP TOTAL_SCRAP, 
RUN_STANDARD,  
S_TOTAL_WORKING_DURATION_100, 
S_LUNCH_IRUPT,  
S_HOT_IRUPT, 
S_INSPECTION_IRUPT, 
S_PROTOTYPE_IRUPT, 
S_CLEANING_IRUPT, 
S_MAINTENANCE_IRUPT, 
S_MEETING_IRUPT, 
S_MOVING_IRUPT, 
S_REWORK_IRUPT, 
S_SETUP_RESET_IRUPT, 
S_TRAINING_IRUPT, 
S_PROD_QTY, 
S_DAMAGAED_SCRAP + 
S_SETUP_SCRAP + 
S_OPERATOR_SCRAP + 
S_MACHINE_SCRAP + 
S_OBSOLETE_SCRAP + 
S_RETURN_SCRAP + 
S_REGULAR_SCRAP + 
S_RUSTED_SCRAP + 
S_DESIGN_SCRAP +
S_OUTSIDE_PROCESS_SCRAP TOTAL_SCRAP, 
SETUP_STANDARD 
from IFSINFO.prl_labor_rpt_new 
WHERE ACCOUNT_DATE BETWEEN TO_DATE('&FROM_DATE','YYYYMMDD') AND TO_DATE('&END_DATE','YYYYMMDD')