select op_id, 'RUN' as OP_INFO_CODE, emp_no, part_no, account_date, work_center_no MCH_CODE, ORDER_NO, R_TOTAL_WORKING_DURATION_100 WORK_HOURS, 
'0' AS FIRST_PEACE_INSP,
R_PROD_QTY PROD_QTY_COMPLETED, (R_DAMAGAED_SCRAP + R_SETUP_SCRAP + R_OPERATOR_SCRAP + R_MACHINE_SCRAP + R_OBSOLETE_SCRAP +
R_RETURN_SCRAP + R_REGULAR_SCRAP + R_OUTSIDE_PROCESS_SCRAP + R_DESIGN_SCRAP) TOTAL_SCRAP 
,(CASE WHEN R_TOTAL_WORKING_DURATION_100 = 0 THEN
0
ELSE
(R_PROD_QTY / R_TOTAL_WORKING_DURATION_100)
END) AS UNITS_PER_HOUR, RUN_STANDARD, 0 AS SETUP_STANDARD
from IFSINFO.prl_labor_rpt_new_ial
UNION
select op_id, 'SETUP' as OP_INFO_CODE, emp_no, part_no, account_date, work_center_no MCH_CODE, ORDER_NO, S_TOTAL_WORKING_DURATION_100 WORK_HOURS, R_INSPECTION_IRUPT AS FIRST_PEACE_INSP,
S_PROD_QTY PROD_QTY_COMPLETED, (S_DAMAGAED_SCRAP + S_SETUP_SCRAP + S_OPERATOR_SCRAP + S_MACHINE_SCRAP + S_OBSOLETE_SCRAP +
S_RETURN_SCRAP + S_REGULAR_SCRAP + S_OUTSIDE_PROCESS_SCRAP + S_DESIGN_SCRAP) TOTAL_SCRAP 
,0 AS UNITS_PER_HOUR, 0 AS RUN_STANDARD, SETUP_STANDARD

select * from IFSINFO.prl_labor_rpt_new_ial where account_date between to_date('7/10/2007','mm/dd/yyyy') and
to_date('7/13/2007','mm/dd/yyyy')


SELECT * FROM IFSINFO.PRL_LABOR_RPT_NEW_IAL

SELECT OP_ID, OP_INFO_CODE, EMP_NO, PART_NO, ACCOUNT_DATE, MCH_CODE, ORDER_NO, WORK_HOURS,  
PROD_QTY_COMPLETED, TOTAL_SCRAP, UNITS_PER_HOUR, RUN_STANDARD, SETUP_STANDARD,
(CASE WHEN OP_INFO_CODE = 'RUN' AND RUN_STANDARD > 0 THEN 
(UNITS_PER_HOUR/RUN_STANDARD)
ELSE
0 END) RUN_VARIANCE
, (CASE WHEN OP_INFO_CODE = 'SETUP' AND WORK_HOURS > 0 THEN
(SETUP_STANDARD / WORK_HOURS)
ELSE
0 END) SETUP_VARIANCE
FROM ZABDA01_LABOR_RPT





SELECT OP_ID, OP_INFO_CODE, EMP_NO, PART_NO, ACCOUNT_DATE, MCH_CODE, ORDER_NO, WORK_HOURS,
FIRST_PEACE_INSP,  
PROD_QTY_COMPLETED, TOTAL_SCRAP, UNITS_PER_HOUR, RUN_STANDARD, SETUP_STANDARD,
(CASE WHEN OP_INFO_CODE = 'RUN' AND RUN_STANDARD > 0 THEN 
(UNITS_PER_HOUR/RUN_STANDARD)
ELSE
0 END) RUN_VARIANCE
, (CASE WHEN OP_INFO_CODE = 'SETUP' AND WORK_HOURS > 0 THEN
((SETUP_STANDARD + FIRST_PEACE_INSP) / WORK_HOURS)
ELSE
0 END) SETUP_VARIANCE
FROM IFSINFO.ZABDA01_LABOR_RPT
WHERE ACCOUNT_DATE BETWEEN TO_DATE(&BEGIN_DATE, 'YYYYMMDD')
AND TO_DATE(&END, 'YYYYMMDD')
ORDER BY ACCOUNT_DATE, OP_ID, OP_INFO_CODE