SELECT OP.ORDER_NO, OP.OP_ID, OP.OP_NO, OP.ACCOUNT_DATE, OP.DEPARTMENT,
OP.WORK_CENTER_NO, OP.OP_INFO_CODE, OP.MCH_CODE, OP.HOURS_CLOCKED, OP.NUM_OPERATORS, OP.STD_CREW_SIZE,
NULL STANDARD_LABOR_SETUP_TIME, OP.LABOR_RUN_STANDARD, OP.UNITS, 
(SELECT QTY.OP_QTY FROM IFSINFO.PRL_LABOR_QTY_CREW QTY WHERE OP.OP_ID = QTY.OP_ID AND OP.OP_NO = QTY.OP_NO AND OP.ACCOUNT_DATE = QTY.ACCOUNT_DATE) QTY_PRODUCED 
FROM IFSINFO.PRL_LABOR_OP_CREW OP
WHERE UPPER(OP.OP_INFO_CODE) = 'RUN'
AND OP.ACCOUNT_DATE = TO_DATE('11/17/2009','MM/DD/YYYY')
--AND OP.OP_ID = 820320
UNION
SELECT OP.ORDER_NO, OP.OP_ID, OP.OP_NO, OP.ACCOUNT_DATE, OP.DEPARTMENT,
OP.WORK_CENTER_NO, OP.OP_INFO_CODE, OP.MCH_CODE, OP.HOURS_CLOCKED, OP.NUM_OPERATORS, NULL,
OP.LABOR_SETUP_TIME, NULL, NULL, NULL FROM IFSINFO.PRL_LABOR_OP_CREW OP
WHERE UPPER(OP.OP_INFO_CODE) = 'SETUP'
AND OP.ACCOUNT_DATE = TO_DATE('11/17/2009','MM/DD/YYYY')
--AND OP.OP_ID = 820320





SELECT * FROM IFSINFO.PRL_LABOR_OP_CREW WHERE OP_ID = 820320 AND ACCOUNT_DATE = TO_DATE('11/13/2009','MM/DD/YYYY')




SELECT * FROM OP_RESULT_SUMMARY WHERE OP_ID = 820320




select RES.order_no, RES.op_id, RES.op_no, RES.account_date, RES.org_code DEPARTMENT, 
RES.work_center_no, RES.op_info_code, RES.MCH_CODE, 
sum(RES.work_hours)Hours_Clocked, count(RES.op_id) num_operators, SHOP.CREW_SIZE STD_CREW_SIZE, 
SHOP.LABOR_RUN_FACTOR LABOR_RUN_STANDARD, SHOP.RUN_TIME_CODE UNITS
from op_result RES, SHOP_ORDER_OPERATION SHOP
WHERE UPPER(RES.OP_INFO_CODE) = 'RUN'
AND RES.ORDER_NO = SHOP.ORDER_NO AND RES.OP_NO = SHOP.OPERATION_NO
AND RES.ORDER_NO = '678853'
group by RES.order_no, RES.op_id, RES.op_no, RES.account_date, RES.org_code, 
RES.work_center_no, RES.op_info_code, RES.MCH_CODE, SHOP.CREW_SIZE,SHOP.RUN_TIME_CODE,
SHOP.LABOR_RUN_FACTOR





SELECT * FROM IFSINFO.PRL_LABOR_QTY_CREW WHERE OP_ID = 820320


select QTY.OP_ID, QTY.ACCOUNT_DATE, QTY.OP_NO, 
QTY.WORK_CENTER_NO, SUM(QTY.OP_QTY) OP_QTY
FROM OP_QUANTITY QTY WHERE OP_ID = 820114
GROUP BY QTY.OP_ID, QTY.ACCOUNT_DATE, QTY.OP_NO, QTY.WORK_CENTER_NO




SELECT * FROM SHOP_ORDER_OPERATION WHERE ORDER_NO = '678853'