SELECT PART_NO, PLANNER_BUYER, SO_ORDER_NO, REQ_QTY, QTY_COMPLETE, (QTY_COMPLETE - REQ_QTY) DIFFERENCE 
FROM IFSINFO.PRL_MPS_REQ_VS_ACT
WHERE TRUNC(DATE_ENTERED) BETWEEN TO_DATE('12/1/2006','MM/DD/YYYY') AND TO_DATE('12/31/2006','MM/DD/YYYY')
AND PLANNER_BUYER IN ('MPS','FAB','CNC/PUNCH','LASER','PURCHASE','WELD')
ORDER BY PLANNER_BUYER

SELECT * FROM IFSINFO.PRL_MPS_REQ_VS_ACT


-- VIEW CREATED FROM CODE BELOW,

SELECT B.PART_NO, IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER(CONTRACT, PART_NO) PLANNER_BUYER, 
A.SO_ORDER_NO, SUM(A.PLANNED_ORDER_REC) AS REQ_QTY, B.QTY_COMPLETE, A.DATE_ENTERED, B.CLOSE_DATE
FROM 
IFSAPP.PROPOSAL_TO_ORDER A JOIN IFSAPP.SHOP_ORD B
ON A.SO_ORDER_NO = B.ORDER_NO
WHERE UPPER(B.STATE) = 'CLOSED' AND B.DATE_ENTERED >= SYSDATE-30
GROUP BY A.SO_ORDER_NO, B.PART_NO, IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER(CONTRACT, PART_NO), B.QTY_COMPLETE, B.STATE
, A.DATE_ENTERED, B.CLOSE_DATE


SELECT * FROM SHOP_ORD_TAB WHERE ORDER_NO = '481079'

SELECT * FROM PROPOSAL_TO_ORDER WHERE SO_ORDER_NO = '476889'

