select PART_NO, 
IFSAPP.INV_PART_3MO_USAGE(PART_NO) AVG_3MONTH_USAGE,
CEIL(IFSAPP.INV_PART_3MO_USAGE(PART_NO) / 90) AVG_DAILY_USAGE,
IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) TOTAL,
IFSAPP.inventory_part_in_stock_api.Get_Sales_Plannable_Qty_Res(CONTRACT,PART_NO,'*') QTY_RESERVED,
IFSAPP.inventory_part_in_stock_api.Get_Qty_In_Quality_Control(CONTRACT, PART_NO,'*') QTY_QC,
IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) -
IFSAPP.inventory_part_in_stock_api.Get_Sales_Plannable_Qty_Res(CONTRACT,PART_NO,'*') -
IFSAPP.inventory_part_in_stock_api.Get_Qty_In_Quality_Control(CONTRACT, PART_NO,'*') ON_HAND
FROM IFSAPP.INVENTORY_PART 
--WHERE PLANNER_BUYER = 'MPS'
where PART_NO = 'PM20' AND CONTRACT = 'MP'


SELECT PART_NO, AVG_3MONTH_USAGE MONTHLY_USAGE_3M_AVG, 
round(IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, 15, 15, 30, 40),0) WMD_15_15_30_40,
TOTAL ON_HAND,
AVG_DAILY_USAGE, ON_HAND AVAILABLE, TRUNC(ON_HAND / (AVG_DAILY_USAGE+1)) DAYS_ONHAND_AVAIL,
IFSAPP.INVENTORY_PART_PLANNING_API.GET_SAFETY_STOCK('MP', PART_NO) SAFETY_STOCK, 
CASE
WHEN IFSAPP.INVENTORY_PART_PLANNING_API.GET_SAFETY_STOCK('MP', PART_NO) = 0 
THEN 0
ELSE
ROUND((ON_HAND)/(IFSAPP.INVENTORY_PART_PLANNING_API.GET_SAFETY_STOCK('MP', PART_NO)),2) END PERCENT_SS_AVAIL,
CASE
WHEN IFSAPP.INVENTORY_PART_PLANNING_API.GET_SAFETY_STOCK('MP', PART_NO) = 0 
THEN 0
ELSE
ROUND((TOTAL)/(IFSAPP.INVENTORY_PART_PLANNING_API.GET_SAFETY_STOCK('MP', PART_NO)),2) END PERCENT_SS_ONHAND
FROM IFSINFO.PRL_MPS_ONHAND_ANALYSIS


ROUND(IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) / 20, 0) DAYS_ONHAND

SELECT IFSAPP.EOL_GET_SHOP_ORD_WIP('LCC-18-C','MP') FROM DUAL


select * from IFSINFO.PRL_WGHT_DEM_MS_MNTH_SUM
WHERE IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER('MP',PART) = 'TUBE_CELL'