/*
CREATE OR REPLACE FUNCTION MPS_Get_Current_Day(
part_no_ IN VARCHAR2 ) RETURN DATE
IS
pass_date_ date;
CURSOR GET_CUR_DATE IS
SELECT CURRENT_DAY
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_date_;
CLOSE GET_CUR_DATE;
RETURN pass_date_;
END;
*/
/*
CREATE OR REPLACE FUNCTION MPS_Get_Demand_Date(
part_no_ IN VARCHAR2 ) RETURN DATE
IS
pass_date_ date;
CURSOR GET_CUR_DATE IS
SELECT DEMAND_TF_DATE
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_date_;
CLOSE GET_CUR_DATE;
RETURN pass_date_;
END;
*/
/*
CREATE OR REPLACE FUNCTION MPS_Get_Planning_Date(
part_no_ IN VARCHAR2 ) RETURN DATE
IS
pass_date_ date;
CURSOR GET_CUR_DATE IS
SELECT PLANNING_TF_DATE
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_date_;
CLOSE GET_CUR_DATE;
RETURN pass_date_;
END;
*/
/*
CREATE OR REPLACE FUNCTION MPS_Get_Current_Counter(
part_no_ IN VARCHAR2 ) RETURN NUMBER
IS
pass_counter_ number;
CURSOR GET_CUR_DATE IS
SELECT CURRENT_COUNTER
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_counter_;
CLOSE GET_CUR_DATE;
RETURN pass_counter_;
END;
*/
/*
CREATE OR REPLACE FUNCTION MPS_Get_Dem_Counter(
part_no_ IN VARCHAR2 ) RETURN NUMBER
IS
pass_counter_ number;
CURSOR GET_CUR_DATE IS
SELECT DEM_COUNTER
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_counter_;
CLOSE GET_CUR_DATE;
RETURN pass_counter_;
END;
*/
CREATE OR REPLACE FUNCTION MPS_Get_Lst_Counter(
part_no_ IN VARCHAR2 ) RETURN NUMBER
IS
pass_counter_ number;
CURSOR GET_CUR_DATE IS
SELECT LAST_COUNTER
FROM IFSINFO.MPS_TF_DATES_IAL
WHERE PART_NO = PART_NO_;
BEGIN
OPEN GET_CUR_DATE;
FETCH GET_CUR_DATE INTO pass_counter_;
CLOSE GET_CUR_DATE;
RETURN pass_counter_;
END;
