select IFSAPP.PURCHASE_ORDER_API.GET_VENDOR_NO(IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Order_No(contract,part_no,MRP_ORDER_SEQ)) PO_SUPPLIER_NO,
       IFSAPP.SUPPLIER_API.GET_VENDOR_NAME(IFSAPP.PURCHASE_ORDER_API.GET_VENDOR_NO(IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Order_No(contract,part_no,MRP_ORDER_SEQ))) SUPPLIER_NAME,
       PART_NO, 
       PART_DESCRIPTION,
       MRP_MESSAGE_CONDITION,
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Order_No(contract,part_no,MRP_ORDER_SEQ) ORDER_NO,
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Line_No(contract,part_no,MRP_ORDER_SEQ) LINE_NO, 
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Release_No(contract,part_no,MRP_ORDER_SEQ) REL_NO,
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Supply_Qty( CONTRACT, PART_NO, MRP_ORDER_SEQ ) SUPPLY_QTY,
       UNIT_MEAS,
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Revised_Due_Date(contract,part_no,MRP_ORDER_SEQ) DUE_DATE,
       IFSAPP.MRP_ORDER_AVAILABILITY_API.Get_Applied_Date(contract,part_no,MRP_ORDER_SEQ) APPLIED_DATE,
       IFSAPP.MRP_PART_EVENT_API.Get_Mrp_Start_Date(contract,part_no,EVENT_COUNTER) START_DATE,
       CREATE_DATE
from ifsapp.MRP_PART_ACTION_PER_SETUP
where contract = 'MP'
order by 1, 3, 5, 6, 7, 8