select A.CONTRACT
,A.PART_NO
,A.VENDOR_NO
,ROUND(A.LIST_PRICE,2) PRICE
,B.BUY_UNIT_PRICE
,((B.BUY_UNIT_PRICE) - ROUND(A.LIST_PRICE,2)) CONTRACT_VS_PO
,B.BUY_QTY_DUE
,(ROUND(A.LIST_PRICE,2) * B.BUY_QTY_DUE) EXTENDED_CONTRACT_PRICE
,(B.BUY_UNIT_PRICE * B.BUY_QTY_DUE) EXTENDED_PO_LINE_PRICE
,(B.BUY_UNIT_PRICE * B.BUY_QTY_DUE) - (ROUND(A.LIST_PRICE,2) * B.BUY_QTY_DUE) EXTENDED_CONTRACT_VS_PO
,B.ORDER_NO
,B.LINE_NO
,B.RELEASE_NO
,B.DATE_ENTERED
from purchase_part_supplier a join purchase_order_line_all b 
ON A.PART_NO = B.PART_NO
AND A.VENDOR_NO = B.VENDOR_NO
AND B.DATE_ENTERED > TO_DATE('1/1/2010','MM/DD/YYYY')
where A.CONTRACT = B.CONTRACT 
--AND A.LIST_PRICE <> B.BUY_UNIT_PRICE
AND a.primary_vendor_db = 'Y' 
AND a.CONTRACT = 'MP'
ORDER BY A.PART_NO