--SELECT * 
--select A.ORDER_NO, B.QTY_INVOICED, B.PART_PRICE, B.DISCOUNT, ((B.PART_PRICE * B.QTY_INVOICED) - ((B.DISCOUNT / 100) * (B.PART_PRICE * B.QTY_INVOICED))) AS LINE_TOTAL
SELECT RETURN_MATERIAL_JOIN.RMA_NO, RETURN_MATERIAL_JOIN.RMA_LINE_NO, RETURN_MATERIAL_JOIN.DATE_REQUESTED, 
to_char(RETURN_MATERIAL_JOIN.DATE_REQUESTED,'mm') Period,
to_char(RETURN_MATERIAL_JOIN.DATE_REQUESTED,'yyyy') Fiscal_Year,
RETURN_MATERIAL_JOIN.RETURN_REASON_CODE, RETURN_MATERIAL_JOIN.CONTRACT, RETURN_MATERIAL_JOIN.CUSTOMER_NO, RETURN_MATERIAL_JOIN.SALE_UNIT_PRICE, RETURN_MATERIAL_JOIN.BASE_SALE_UNIT_PRICE, RETURN_MATERIAL_JOIN.QTY_TO_RETURN, RETURN_MATERIAL_JOIN.DATE_RETURNED, RETURN_MATERIAL_JOIN.CATALOG_NO, RETURN_MATERIAL_JOIN.PART_NO, SALES_PART.CONTRACT, SALES_PART.CATALOG_GROUP, SALES_PART.SALES_PRICE_GROUP_ID, CUSTOMER_INFO.NAME 
FROM RETURN_MATERIAL_JOIN JOIN SALES_PART ON RETURN_MATERIAL_JOIN.CONTRACT = SALES_PART.CONTRACT 
AND RETURN_MATERIAL_JOIN.PART_NO = SALES_PART.PART_NO LEFT JOIN CUSTOMER_INFO ON RETURN_MATERIAL_JOIN.CUSTOMER_NO = CUSTOMER_INFO.CUSTOMER_ID
WHERE RETURN_MATERIAL_JOIN.DATE_REQUESTED Between to_date('01012002','mmddyyyy') And to_date ('05152005','mmddyyyy') 
AND SALES_PART.CONTRACT ='MP';
