select  SO.ORDER_NO, SOC.PART_NO, SOC.CLOSE_DATE, SOC.REVISED_QTY_DUE BUILD_QTY, SOC.QTY_COMPLETE,
SOC.TOTAL_STD_ACCUM_COST TOTAL_STANDARD_COST, SOC.TOTAL_ACTUAL_ACCUM_COST TOTAL_ACTUAL_COST, SOC.ACT_STD_ACCUM DIFF,
SOC.ACT_STD_ACCUM_FACTOR PRCT_DIFF  
from shop_ord SO, SHOP_ORDER_COST_OVERVIEW SOC,
ifsinfo.PRL_LAB_ACT_STND_BY_OP_B SOLAB
where TRUNC(SO.CLOSE_DATE,'DD') >= TO_DATE('11/8/2016','MM/DD/YYYY')
and so.contract = 'MP'
AND SO.ORDER_NO = SOC.ORDER_NO (+)
order by SOC.ACT_STD_ACCUM desc


SELECT * FROM SHOP_ORDER_COST_OVERVIEW WHERE ORDER_NO = '1131019'