--all other than welding (TDABC)
select STUPDAY.ORDER_NO, STUPDAY.PART_NO, TRUNC(STUPDAY.DATED,'DD') DATED, 
SUM(STUPDAY.QUANTITY) SO_QTY , STUPDAY.WORK_CENTER_NO,
MAX(STUPDAY.CREW_SIZE) CREW_SIZE, STUPDAY.LABOR_CLASS_NO, STUPDAY.OPERATION_NO,
STUPDAY.OPERATION_DESCRIPTION, MAX(STUPDAY.LABOR_RUN_FACTOR) LABOR_RUN_FACTOR, 
MAX(STUPDAY.LABOR_SETUP_TIME) LABOR_SETUP_TIME
from ifsinfo.PRL_CAPACITY_OORECSTD STUPDAY
WHERE LABOR_CLASS_NO IN ('PRODUCTION', 'LASER', 'CNC','SETUP FAB','SETUP PACK')
GROUP BY
STUPDAY.ORDER_NO, STUPDAY.PART_NO, TRUNC(STUPDAY.DATED,'DD'),
STUPDAY.YEAR, STUPDAY.WORK_CENTER_NO, STUPDAY.LABOR_CLASS_NO, 
STUPDAY.OPERATION_NO, STUPDAY.OPERATION_DESCRIPTION




select * from ifsinfo.prl_capacity_oorecstd

--make this the welding report (TDABC_WELD)


select STUPALL.ORDER_NO, STUPALL.PART_NO, TRUNC(STUPALL.DATED,'DD') DATED,  
STUPALL.QUANTITY SO_QTY, STUPALL.WORK_CENTER_NO,
STUPALL.CREW_SIZE, STUPALL.LABOR_CLASS_NO, STUPALL.OPERATION_NO,
STUPALL.OPERATION_DESCRIPTION, STUPALL.LABOR_RUN_FACTOR, 
STUPALL.LABOR_SETUP_TIME
from ifsinfo.PRL_CAPACITY_OORECSTD STUPALL 
WHERE LABOR_CLASS_NO in ('WELDING','PACKLINE')




















SELECT ORDER_NO, PART_NO, LABOR_CLASS_NO, TRUNC(DATED,'DD'), SUM(QUANTITY), MAX(LABOR_RUN_FACTOR), MAX(LABOR_SETUP_TIME) 
FROM IFSINFO.PRL_CAPACITY_OORECSTD WHERE ORDER_NO = 607151
GROUP BY ORDER_NO, PART_NO, LABOR_CLASS_NO, TRUNC(DATED, 'DD')


--make this the welding report (TDABC_WELD)


select STUPALL.ORDER_NO, STUPALL.PART_NO, TRUNC(STUPALL.DATED,'DD') DATED,  
STUPALL.YEAR, STUPALL.QUANTITY, STUPALL.WORK_CENTER_NO,
STUPALL.CREW_SIZE, STUPALL.LABOR_CLASS_NO, STUPALL.OPERATION_NO,
STUPALL.OPERATION_DESCRIPTION, STUPALL.LABOR_RUN_FACTOR, 
STUPALL.LABOR_SETUP_TIME
from ifsinfo.PRL_CAPACITY_OORECSTD STUPALL 
WHERE LABOR_CLASS_NO = 'WELDING'








-------------------other sql

select STUPALL.ORDER_NO, STUPALL.PART_NO, TRUNC(STUPALL.DATED,'DD') DATED,  
STUPALL.YEAR, STUPALL.QUANTITY, STUPALL.WORK_CENTER_NO,
STUPALL.CREW_SIZE, STUPALL.LABOR_CLASS_NO, STUPALL.OPERATION_NO,
STUPALL.OPERATION_DESCRIPTION, STUPALL.LABOR_RUN_FACTOR, 
STUPALL.LABOR_SETUP_TIME
from ifsinfo.PRL_CAPACITY_OORECSTD STUPALL 
WHERE LABOR_CLASS_NO = 'WELDING' and order_no = '638539'
group by stupall.order_no, stupall.part_no, stupall.dated, stupall.year
,stupall.quantity, stupall.work_center_no, stupall.crew_size, stupall.labor_class_no,
stupall.operation_no,
stupall.operation_description, stupall.labor_run_factor,
stupall.labor_setup_time
UNION


