select PLANNER_BUYER PLANNER, PART_NO, DESCRIPTION, PRL_GET_DEMAND(part_no, CONTRACT, 14) as DEMAND_14_DAYS,
IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) -
IFSAPP.inventory_part_in_stock_api.Get_Sales_Plannable_Qty_Res(CONTRACT,PART_NO,'*') -
IFSAPP.inventory_part_in_stock_api.Get_Qty_In_Quality_Control(CONTRACT, PART_NO,'*') AVAILABLE_ONHAND,
IFSAPP.INVENTORY_PART_PLANNING_API.Get_Safety_Stock(CONTRACT, PART_NO) SAFETY_STOCK,
IFSAPP.INVENTORY_PART_PLANNING_API.Get_Std_Order_Size(CONTRACT, PART_NO) STD_LOT_SIZE
FROM IFSAPP.INVENTORY_PART
WHERE PART_NO IN ('ADJ0305','EXT006')
AND CONTRACT = 'MP'