SELECT PART_NO, IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER('BBG',PART_NO) PLANNER,
IFSAPP.MPS_EVALUATE_FLAG(IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4), 
IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL),
IFSAPP.MPS_GET_AVAILABLE(PART_NO),
IFSAPP.INVENTORY_PART_PLANNING_API.Get_safety_stock(CONTRACT, PART_NO),
round(IFSAPP.MPS_Get_Current_Forecast(contract, part_no, sysdate),2), 
round(IFSAPP.MPS_GET_AVAILABLE(PART_NO) / (IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4)/21),0))
FLAG,  
ROUND(IFSAPP.INVENTORY_PART_COST_API.Get_Part_Cost(contract, part_no), 2) COST_PER_UNIT,
round(IFSAPP.MPS_Get_Current_Forecast(contract, part_no, sysdate),2) FORECAST_CURR_MONTH,
round(IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4),0) WEIGHTED_MONTHLY_DEMAND,
IFSAPP.ORDER_SUPPLY_DEMAND_API.GET_SUM_QTY_DEMAND('BBG',PART_NO, '*') OPEN_ORDERS,
IFSAPP.MPS_GET_AVAILABLE(PART_NO) ONHAND_AVAILABLE,
IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) ON_HAND,
IFSAPP.INVENTORY_PART_PLANNING_API.Get_safety_stock(CONTRACT, PART_NO) SAFETY_STOCK,
round(IFSAPP.MPS_GET_AVAILABLE(PART_NO) / (IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4)/21),0) DAYS_ONHAND_AVAILABLE
FROM IFSAPP.INVENTORY_PART
WHERE CONTRACT = 'BBG'
--AND IFSAPP.INVENTORY_PART_API.GET_PLANNER_BUYER('MP',PART_NO) IN ('MPS_PRIORITY','MPS','TUBE_CELL')
GROUP BY PART_NO, CONTRACT