SELECT VOUCHER_NO, ROW_NO, ACCOUNTING_YEAR, ACCOUNTING_PERIOD, VOUCHER_DATE, AMOUNT FROM GEN_LED_VOUCHER_ROW_UNION_QRY
WHERE ACCOUNTING_YEAR = 2006 AND ACCOUNTING_PERIOD IN (1,2,3,4) AND ACCOUNT = '7550'
AND TEXT = 'UNITED PARCEL SERVICE    (MP)'