select A.PARTY_TYPE_ID, A.REFERENCE_SERIE, A.REFERENCE_NUMBER, A.OPTIONAL_CODE TAX_CODE, 
SUM(A.AMOUNT * -1) TAX_AMT_GBP, SUM(A.CURRENCY_AMOUNT * -1) TAX_AMT_CURR, 
A.CURRENCY_CODE, B.INVOICE_NO, B.INVOICE_DATE, 
B.VOUCHER_NO_REF, B.VOU_DATE, B.GROSS_AMOUNT, B.NET_AMOUNT
from ifsapp.gen_led_voucher_row_union_qry a, IFSAPP.OUTGOING_INVOICE_QRY B
where a.company = b.company
and a.voucher_no = B.VOUCHER_NO_REF
and A.VOUCHER_TYPE = B.VOUCHER_TYPE_REF
and a.voucher_date between to_date('6/1/2011','mm/dd/yyyy') and to_date('6/30/2011','mm/dd/yyyy')
and a.account = '3295'
and a.voucher_type = 'F'
AND A.OPTIONAL_CODE NOT IN ('0','1')
GROUP BY A.PARTY_TYPE_ID, A.REFERENCE_SERIE, A.REFERENCE_NUMBER, A.OPTIONAL_CODE, A.CURRENCY_CODE, B.INVOICE_NO, B.INVOICE_DATE, 
B.VOUCHER_NO_REF, B.VOU_DATE, B.GROSS_AMOUNT, B.NET_AMOUNT



SELECT * FROM OUT_INVOICE_UTIL_INV_ITEM_PUB C WHERE C.COMPANY = '31' AND C.INVOICE_NO = '1127183'


SELECT * FROM ifsapp.gen_led_voucher_row_union_qry a WHERE A.COMPANY = '31' AND A.REFERENCE_NUMBER = '1127183'