select * from ifsapp.part_serial_catalog

select A.KEY_VALUE, (SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XACT_CODE') XACT_CODE from ifsapp.technical_specification_attr A where A.key_value like '%1701VKDN47O001%' AND A.ATTRIBUTE = 'XACT_CODE'

select A.KEY_VALUE "Model / Serial Number", (SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XACT_CODE') "Activation Code"  
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XIMEI') IMEI 
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XMAC') "MODEM MAC"
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XMEID') MEID
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XSER_NUM_MOD') "MODEM SERIAL NUMBER"
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XSIM') "SIM CARD"
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XPUSHMAC') "PUSH MAC"
,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XSER_NUM_EKM') "EKM METER SERIAL NO"
--,(SELECT B.VALUE_TEXT FROM IFSAPP.TECHNICAL_SPECIFICATION_ATTR B WHERE A.KEY_VALUE = B.KEY_VALUE AND B.ATTRIBUTE = 'XULV3') XULV3
from ifsapp.technical_specification_attr A where (A.key_value like '%K1CSHYBR47MPSUB%' AND A.ATTRIBUTE = 'XACT_CODE') OR 
((A.key_value like '%K1CSDIGT47SUB%' AND A.ATTRIBUTE = 'XACT_CODE'))