SELECT PART_NO,
IFSAPP.MPS_EVALUATE_FLAG(IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4), 
IFSAPP.MPS_GET_AVAILABLE(PART_NO),
IFSAPP.INVENTORY_PART_PLANNING_API.Get_safety_stock(CONTRACT, PART_NO),
round(IFSAPP.MPS_Get_Current_Forecast(contract, part_no, sysdate),2), 1,
TRUNC(IFSAPP.MPS_GET_DAYS_ONHAND(PART_NO)))
FLAG,  
ROUND(IFSAPP.INVENTORY_PART_COST_API.Get_Part_Cost(contract, part_no), 2) COST_PER_UNIT,
round(IFSAPP.MPS_Get_Current_Forecast(contract, part_no, sysdate),2) FORECAST_CURR_MONTH,
round(IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4),0) WEIGHTED_MONTHLY_DEMAND,
IFSAPP.LEVEL_1_FORECAST_UTIL_API.get_sum_act_dem(contract, part_no, NVL(MS_SET,1), 1, IFSAPP.mps_get_lst_counter(part_no)) OPEN_ORDERS,
IFSAPP.MPS_GET_AVAILABLE(PART_NO) ONHAND,
IFSAPP.INVENTORY_PART_PLANNING_API.Get_safety_stock(CONTRACT, PART_NO) SAFETY_STOCK,
round((IFSAPP.INVENTORY_PART_IN_STOCK_API.Get_Inventory_Qty_Onhand(CONTRACT,PART_NO,NULL) / (IFSAPP.PRL_WGHT_DEM_Get_Weighted_Ave(part_no, &MONTH_1, &MONTH_2, &MONTH_3, &MONTH_4)/21)),0) DAYS_ONHAND,
MS_SET
FROM IFSAPP.LEVEL_1_FORECAST
WHERE MS_SET = &MS_SET
GROUP BY PART_NO, CONTRACT, MS_SET