CREATE TABLESPACE ver_tps92 DATAFILE 'D:\ORADATA\PROD\fnd_vertps92.dbf' SIZE 2400M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_gis92 DATAFILE 'D:\ORADATA\PROD\fnd_vergis92.dbf' SIZE 1200M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_utl92 DATAFILE 'D:\ORADATA\PROD\fnd_verutl92.dbf' SIZE 25M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_jrl92 DATAFILE 'D:\ORADATA\PROD\fnd_verjrl92.dbf' SIZE 1500M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

CREATE TABLESPACE ver_rpt92 DATAFILE 'D:\ORADATA\PROD\fnd_verrpt92.dbf' SIZE 3100M
AUTOEXTEND ON NEXT 10M MAXSIZE unlimited;

--Creates users for Vertex Project and assignes required access
--VER_TPS, VER_GIS, VER_JRL, VER_RPT, VER_UTL
CREATE USER "VER_TPS92" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_TPS92" 
QUOTA UNLIMITED 
ON "VER_TPS92" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_TPS92";
GRANT CREATE ANY TABLE TO "VER_TPS92";
--GRANT CREATE ANY OBJECT TO "VER_TPS9";
GRANT CREATE ANY VIEW TO "VER_TPS92";
GRANT DROP ANY VIEW TO "VER_TPS92";
GRANT CREATE ANY SEQUENCE TO "VER_TPS92";
GRANT CREATE ANY TRIGGER TO "VER_TPS92";
GRANT SELECT ANY TABLE TO "VER_TPS92";
GRANT CONNECT TO "VER_TPS92";

CREATE USER "VER_GIS92" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_GIS92" 
QUOTA UNLIMITED 
ON "VER_GIS92" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_GIS92";
GRANT CREATE ANY TABLE TO "VER_GIS92";
--GRANT CREATE ANY OBJECT TO "VER_GIS9";
GRANT CREATE ANY VIEW TO "VER_GIS92";
GRANT DROP ANY VIEW TO "VER_GIS92";
GRANT CREATE ANY SEQUENCE TO "VER_GIS92";
GRANT CREATE ANY TRIGGER TO "VER_GIS92";
GRANT SELECT ANY TABLE TO "VER_GIS92";
GRANT CONNECT TO "VER_GIS92";

CREATE USER "VER_JRL92" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_JRL92" 
QUOTA UNLIMITED 
ON "VER_JRL92" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_JRL92";
GRANT CREATE ANY TABLE TO "VER_JRL92";
--GRANT CREATE ANY OBJECT TO "VER_JRL9";
GRANT CREATE ANY VIEW TO "VER_JRL92";
GRANT DROP ANY VIEW TO "VER_JRL92";
GRANT CREATE ANY SEQUENCE TO "VER_JRL92";
GRANT CREATE ANY TRIGGER TO "VER_JRL92";
GRANT SELECT ANY TABLE TO "VER_JRL92";
GRANT CONNECT TO "VER_JRL92";

CREATE USER "VER_RPT92" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_RPT92" 
QUOTA UNLIMITED 
ON "VER_RPT92" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_RPT92";
GRANT CREATE ANY TABLE TO "VER_RPT92";
--GRANT CREATE ANY OBJECT TO "VER_RPT9";
GRANT CREATE ANY VIEW TO "VER_RPT92";
GRANT DROP ANY VIEW TO "VER_RPT92";
GRANT CREATE ANY SEQUENCE TO "VER_RPT92";
GRANT CREATE ANY TRIGGER TO "VER_RPT92";
GRANT SELECT ANY TABLE TO "VER_RPT92";
GRANT CONNECT TO "VER_RPT92";

CREATE USER "VER_UTL92" --PROFILE "DEFAULT" 
IDENTIFIED BY "INTERNAL" DEFAULT TABLESPACE "VER_UTL92" 
QUOTA UNLIMITED 
ON "VER_UTL92" 
ACCOUNT UNLOCK;
GRANT CREATE ANY INDEX TO "VER_UTL92";
GRANT CREATE ANY TABLE TO "VER_UTL92";
--GRANT CREATE ANY OBJECT TO "VER_UTL9";
GRANT CREATE ANY VIEW TO "VER_UTL92";
GRANT DROP ANY VIEW TO "VER_UTL92";
GRANT CREATE ANY SEQUENCE TO "VER_UTL92";
GRANT CREATE ANY TRIGGER TO "VER_UTL92";
GRANT SELECT ANY TABLE TO "VER_UTL92";
GRANT CONNECT TO "VER_UTL92";