/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) -- [USERID]
      [FULLNAME]
      --,[TITLE]
      ,[PHONE]
      --,[EMAILADDR]
      --,[FAX]
      --,[DEPT_NUM]
      ,[DEPT]
      ,[LOCATION]
      --,[USERDEF_1]
      --,[USERDEF_2]
      --,[LOGIN]
      --,[PASSWORD]
      --,[PASSWORDFLAGS]
      --,[LANGUAGEID]
      --,[NTAUTHENTICATION]
      --,[NTACCOUNT]
      --,[SID]
      --,[SELFSERVICEACCESS]
      --,[IMAGEPATH]
      --,[COMPFLAG]
      --,[EMPLOYEE_ID]
      --,[SessionId]
  FROM [TRACKIT_DATA].[dbo].[TIUSER]