create table YEAR_OVER_YEAR_SALES_IN(
 IDENTITY VARCHAR(50),
    COMPANY VARCHAR(10),
    INVOICE_DATE DATE,
    CATALOG_NO VARCHAR(100),
    INVOICED_QTY DOUBLE,
    EXTENDED_SALE DOUBLE,
    UNIQUE_KEY VARCHAR(100) NOT NULL,
    USD_EXT_AMOUNT DOUBLE,
    SALES_TYPE VARCHAR(25),
    CUSTOMER VARCHAR(50),
    primary key (UNIQUE_KEY));